### ISSUE TITLE
Crash: ConcurrentModificationError

### ISSUE THREAD

**Issue by nimakarimipour** [nimakarimipour/NullAwayAnnotator#40]
**Describe the bug**
In environment where multiple instances of `Scanner` is running, it is possible that the tool crashes in error prone checks because of mutable static fields. The exception is `ConcurrentModificationError`

**To Reproduce**
Run multiple instance of `Scanner` in parallel.

**Expected behavior**
Stable run of multiple `Scanner` instances.

**Stack trace**
```java
java.util.ConcurrentModificationException
  	at java.base/java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1644)
  	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
  	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
  	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  	at java.base/java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:548)
  	at edu.ucr.cs.riple.scanner.out.MethodInfo.findOrCreate(MethodInfo.java:65)
  	at edu.ucr.cs.riple.scanner.out.MethodInfo.findParent(MethodInfo.java:89)
  	at edu.ucr.cs.riple.scanner.Scanner.matchMethod(Scanner.java:106)
  	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:451)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:741)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:152)
        ......
```

**OS (please complete the following information):**
 - OS: OS X
 - Version 12.5
 - Annotator Version: v1.3.2-SNAPSHOT

**Additional context**
Not-Applicable.

**Comment by msridhar** [comment]
For reference, within Error Prone checkers, a better way to store some kind of "global" cache or state is within the `Context` object, which is unique to each run of the compiler.  E.g., see this code from NullAway:

https://github.com/uber/NullAway/blob/3b90d3b01b98844d302f299e7101a44687cf321d/nullaway/src/main/java/com/uber/nullaway/dataflow/AccessPathNullnessAnalysis.java#L107-L119

You can get the `Context` from the `VisitorState`.  This technique means passing the `VisitorState` around to more places, but it's much safer than mutable static fields.

**Comment by nimakarimipour** [comment]
@msridhar Thank you very much for the advice, I was following the same approach but with storing the state in the config object, but what you suggested is much more cleaner, will overwrite in this way.
